/*
 * Copyright 2026 DDS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.dds.nifi.beats.api;

import java.util.Map;

public record ListenerSnapshot(
        int listeningPort,
        long currentConnections,
        long acceptedConnections,
        long rejectedConnections,
        long queuedEvents,
        long queuedBytes,
        long activeBatches,
        long readyBatches,
        long claimedBatches,
        long framesDecoded,
        long protocolErrors,
        long acknowledgementsSent,
        long acknowledgementFailures,
        long readSuspendedChannels,
        long processingTasks,
        long processingBytes,
        long partialFrameReservedBytes,
        long deferredFrames,
        boolean acceptsPaused,
        boolean globalPressure,
        long compressedFrames,
        long compressedBytes,
        long decompressedBytes,
        long eventsAccepted,
        long eventsCommitted,
        long pressureRetryAttempts,
        long claimsAbandoned,
        long claimFinalizationFailures,
        long disconnectedBeforeCommitEvents,
        long disconnectedAfterCommitEvents,
        long queueAgeAverageMillis,
        long queueAgeMaximumMillis,
        long commitLatencyAverageMillis,
        long commitLatencyMaximumMillis,
        long acknowledgementLatencyAverageMillis,
        long acknowledgementLatencyMaximumMillis,
        long queueAgeP50Millis,
        long queueAgeP95Millis,
        long queueAgeP99Millis,
        long commitLatencyP50Millis,
        long commitLatencyP95Millis,
        long commitLatencyP99Millis,
        long acknowledgementLatencyP50Millis,
        long acknowledgementLatencyP95Millis,
        long acknowledgementLatencyP99Millis,
        long eventsAcceptedPerSecond,
        long eventsCommittedPerSecond,
        long payloadBytesAcceptedPerSecond,
        long payloadBytesCommittedPerSecond,
        long keepAlivesSent,
        long keepAliveFailures,
        long acknowledgementWriteTimeouts,
        long pendingAcknowledgementWrites,
        long frameAssemblyTimeouts,
        long processingExecutorPendingTasks,
        long processingExecutorHottestQueue,
        long processingExecutorHottestQueueMaximum,
        long processingExecutorRejections,
        long cleanupPendingTasks,
        long cleanupPeakPendingTasks,
        long cleanupRejections,
        long cleanupEmergencySubmitted,
        boolean cleanupPressure,
        long tlsConcurrentHandshakes,
        long tlsPeakConcurrentHandshakes,
        long tlsHandshakeTimeouts,
        long tlsHandshakeLatencyP50Millis,
        long tlsHandshakeLatencyP95Millis,
        long tlsHandshakeLatencyP99Millis,
        long firstByteTimeouts,
        long idleConnectionTimeouts,
        long eventLoopLagCurrentMillis,
        long eventLoopLagMaximumMillis,
        long eventLoopLagOver50Millis,
        long eventLoopLagOver100Millis,
        long eventLoopLagOver1000Millis,
        String eventFilteringMode,
        long configuredFilterRules,
        long indexedFilterRules,
        long unindexedFilterRules,
        long filterReferencedPaths,
        long filterAnchorPaths,
        long filterBatchPaths,
        long filterEventsEvaluated,
        long filterCandidateRulesSelected,
        long filterRuleEvaluations,
        long filterJsonPasses,
        long filterValuesExtracted,
        double filterCandidateRulesAverage,
        double filterRuleEvaluationsAverage,
        double filterJsonPassesAverage,
        double filterValuesExtractedAverage,
        long filterEventsInput,
        long filterEventsKept,
        long filterEventsDropped,
        long filterBytesDropped,
        long filterEvaluationErrors,
        Map<String, Long> filterRuleMatches,
        Map<String, Long> connectionCloseReasons) {
}
