/*
 * Copyright 2026 DDS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.dds.nifi.beats.server;

import com.dds.nifi.beats.model.BatchReceipts;
import com.dds.nifi.beats.model.ConnectionToken;
import io.netty.channel.ChannelFuture;
import io.netty.util.concurrent.ScheduledFuture;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;

/** Commit receipt to ordered cumulative ACK bridge with bounded ACK write deadlines. */
public final class AckCoordinator {
    private final ConnectionRegistry registry;
    private final ProcessorMetrics metrics;
    private final PressureController pressure;
    private final long acknowledgementWriteTimeoutMillis;
    private final long protocolKeepAliveNanos;
    private final AtomicLong nextKeepAliveScanNanos = new AtomicLong();

    public AckCoordinator(
            final ConnectionRegistry registry,
            final ProcessorMetrics metrics,
            final PressureController pressure,
            final Duration acknowledgementWriteTimeout,
            final Duration protocolKeepAliveInterval) {
        this.registry = registry;
        this.metrics = metrics;
        this.pressure = pressure;
        this.acknowledgementWriteTimeoutMillis = acknowledgementWriteTimeout.toMillis();
        this.protocolKeepAliveNanos = protocolKeepAliveInterval.isZero()
                ? 0L : protocolKeepAliveInterval.toNanos();
        this.nextKeepAliveScanNanos.set(System.nanoTime() + Math.max(1L, protocolKeepAliveNanos));
    }

    public void committed(final BatchReceipts receipts) {
        final Map<ConnectionToken, RangeBuffer> byConnection = new LinkedHashMap<>();
        for (int index = 0; index < receipts.runCount(); index++) {
            byConnection.computeIfAbsent(receipts.runConnection(index), ignored -> new RangeBuffer())
                    .add(receipts.runWindowId(index), receipts.runFirstSequence(index), receipts.runEventCount(index));
        }

        byConnection.forEach((token, ranges) -> {
            final ConnectionState state = registry.get(token);
            if (state == null || !state.channel().isActive()) {
                return;
            }
            try {
                state.channel().eventLoop().execute(() -> acknowledgeCommitted(state, ranges));
            } catch (RuntimeException e) {
                failAfterCommit(state);
            }
        });
    }

    /**
     * Marks an intentionally filtered sequence range accepted without a NiFi FlowFile. The range
     * still participates in the same ordered cumulative ACK frontier as committed retained events.
     */
    public void acceptedWithoutFlowFile(
            final ConnectionState state,
            final long windowId,
            final long firstSequence,
            final int eventCount) {
        if (eventCount <= 0 || !state.channel().isActive()) {
            return;
        }
        try {
            state.channel().eventLoop().execute(() -> {
                try {
                    final List<ConnectionState.CommitAdvance> advances =
                            state.commitRange(windowId, firstSequence, eventCount);
                    pressure.outstandingCapacityReleased(state);
                    writeAdvances(state, advances);
                } catch (RuntimeException e) {
                    metrics.acknowledgementFailures.increment();
                    close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
                }
            });
        } catch (RuntimeException e) {
            metrics.acknowledgementFailures.increment();
            close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
        }
    }

    /** Schedules ACKs generated by protocol-only events such as an ordered zero-length window. */
    public void protocolAdvances(
            final ConnectionState state,
            final List<ConnectionState.CommitAdvance> advances) {
        if (advances == null || advances.isEmpty() || !state.channel().isActive()) {
            return;
        }
        try {
            state.channel().eventLoop().execute(() -> writeAdvances(state, advances));
        } catch (RuntimeException e) {
            metrics.acknowledgementFailures.increment();
            close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
        }
    }

    /** Called from the low-frequency maintenance loop; the connection scan occurs only when due. */
    public void maintenance() {
        if (protocolKeepAliveNanos <= 0) {
            return;
        }
        final long now = System.nanoTime();
        final long due = nextKeepAliveScanNanos.get();
        if (now < due || !nextKeepAliveScanNanos.compareAndSet(due, now + protocolKeepAliveNanos)) {
            return;
        }
        for (ConnectionState state : registry.states()) {
            if (!state.channel().isActive() || state.outstanding() <= 0) {
                continue;
            }
            final long last = state.lastAcknowledgementWriteNanos();
            if (now - last < protocolKeepAliveNanos) {
                continue;
            }
            final ConnectionState.KeepAliveAcknowledgement keepAlive =
                    state.repeatableKeepAliveAcknowledgement();
            if (keepAlive == null) {
                continue;
            }
            state.markAcknowledgementWrite(now); // prevents duplicate scheduling before completion
            try {
                state.channel().eventLoop().execute(() -> writeWithTimeout(
                        state, keepAlive.windowId(), keepAlive.sequence(), true, -1L));
            } catch (RuntimeException e) {
                metrics.keepAliveFailures.increment();
                close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
            }
        }
    }

    private void acknowledgeCommitted(final ConnectionState state, final RangeBuffer ranges) {
        try {
            final List<ConnectionState.CommitAdvance> advances = new ArrayList<>();
            for (int index = 0; index < ranges.size; index++) {
                advances.addAll(state.commitRange(
                        ranges.windowId[index], ranges.first[index], ranges.count[index]));
            }
            pressure.outstandingCapacityReleased(state);
            writeAdvances(state, advances);
        } catch (RuntimeException e) {
            failAfterCommit(state);
        }
    }

    /** Must run on the owning channel event loop to preserve ACK ordering. */
    private void writeAdvances(
            final ConnectionState state,
            final List<ConnectionState.CommitAdvance> advances) {
        if (advances.isEmpty() || !state.channel().isActive()) {
            return;
        }

        for (ConnectionState.CommitAdvance advance : advances) {
            writeWithTimeout(
                    state,
                    advance.windowId(),
                    advance.ackSequence(),
                    false,
                    advance.oldestReceivedNanos());
        }
        state.channel().flush();
    }

    private void writeWithTimeout(
            final ConnectionState state,
            final long windowId,
            final long sequence,
            final boolean keepAlive,
            final long latencyStart) {
        if (!state.channel().isActive()) {
            return;
        }
        if (keepAlive && !state.isRepeatableKeepAliveAcknowledgement(windowId, sequence)) {
            return; // The head window advanced after maintenance selected the repeatable ACK.
        }
        final AtomicBoolean terminal = new AtomicBoolean();
        metrics.pendingAcknowledgementWrites.incrementAndGet();
        if (!state.channel().isWritable()) {
            metrics.acknowledgementUnwritableWrites.increment();
        }

        final ChannelFuture write;
        try {
            write = state.channel().write(sequence);
        } catch (RuntimeException failure) {
            terminal.set(true);
            metrics.pendingAcknowledgementWrites.updateAndGet(value -> Math.max(0L, value - 1L));
            if (keepAlive) {
                metrics.keepAliveFailures.increment();
            } else {
                metrics.acknowledgementFailures.increment();
            }
            close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
            return;
        }

        final ScheduledFuture<?> timeout;
        try {
            timeout = state.channel().eventLoop().schedule(() -> {
                if (terminal.compareAndSet(false, true)) {
                    metrics.pendingAcknowledgementWrites.updateAndGet(value -> Math.max(0L, value - 1L));
                    metrics.acknowledgementWriteTimeouts.increment();
                    if (keepAlive) {
                        metrics.keepAliveFailures.increment();
                    } else {
                        metrics.acknowledgementFailures.increment();
                    }
                    close(state, ConnectionCloseReason.ACK_TIMEOUT);
                }
            }, acknowledgementWriteTimeoutMillis, TimeUnit.MILLISECONDS);
        } catch (RuntimeException failure) {
            if (terminal.compareAndSet(false, true)) {
                metrics.pendingAcknowledgementWrites.updateAndGet(value -> Math.max(0L, value - 1L));
                if (keepAlive) {
                    metrics.keepAliveFailures.increment();
                } else {
                    metrics.acknowledgementFailures.increment();
                }
            }
            close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
            return;
        }

        write.addListener(future -> {
            if (!terminal.compareAndSet(false, true)) {
                return;
            }
            timeout.cancel(false);
            metrics.pendingAcknowledgementWrites.updateAndGet(value -> Math.max(0L, value - 1L));
            if (future.isSuccess()) {
                final long completedNanos = System.nanoTime();
                if (keepAlive) {
                    state.markAcknowledgementWrite(completedNanos);
                } else {
                    state.markAcknowledgementWrite(completedNanos, windowId, sequence);
                }
                if (keepAlive) {
                    metrics.keepAlivesSent.increment();
                } else {
                    metrics.acknowledgementsSent.increment();
                    if (latencyStart >= 0) {
                        metrics.recordAcknowledgementLatency(System.nanoTime() - latencyStart);
                    }
                }
            } else {
                if (keepAlive) {
                    metrics.keepAliveFailures.increment();
                } else {
                    metrics.acknowledgementFailures.increment();
                }
                close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
            }
        });
        if (keepAlive) {
            state.channel().flush();
        }
    }

    private void failAfterCommit(final ConnectionState state) {
        metrics.claimFinalizationFailures.increment();
        metrics.acknowledgementFailures.increment();
        close(state, ConnectionCloseReason.ACK_WRITE_FAILURE);
    }

    private static void close(final ConnectionState state, final ConnectionCloseReason reason) {
        ConnectionCloseTracker.mark(state.channel(), reason);
        state.channel().close();
    }

    /** Primitive range list: one allocation per committed connection, not one boxed receipt per event. */
    private static final class RangeBuffer {
        private long[] windowId = new long[4];
        private long[] first = new long[4];
        private int[] count = new int[4];
        private int size;

        private void add(final long receiptWindowId, final long firstSequence, final int eventCount) {
            if (size == first.length) {
                windowId = Arrays.copyOf(windowId, size << 1);
                first = Arrays.copyOf(first, size << 1);
                count = Arrays.copyOf(count, size << 1);
            }
            windowId[size] = receiptWindowId;
            first[size] = firstSequence;
            count[size] = eventCount;
            size++;
        }
    }
}
